server:
  port: 8082
  servlet:
    contextPath: /
spring:
  application:
    name: npp-service-center
  banner:
    location: "classpath:NppServiceCenter.txt"
  cloud:
    nacos:
      discovery:
        namespace: npp-public
        clusterName: npp-cluster
        server-addr: 127.0.0.1:8848
  mvc:
    servlet:
      loadOnStartup: 1
  profiles:
    active: local
    include: dubbo,mystarter,sharding
logging:
  level:
#    PARAM-RETVAL-PRINTER: debug
    com.myz.npp.service.user.dao.mapper: info
    com.myz.npp.service.accountbook.dao.mapper: info

management:
  endpoints:
    web:
      exposure:
        include: "*"
