# https://github.com/apache/dubbo-spring-boot-project/blob/2.7.x/dubbo-spring-boot-samples/registry-samples/zookeeper-samples/provider-sample/src/main/resources/application.properties
dubbo:
  scan:
    basePackages: com.myz.npp.service.user.rpc,com.myz.npp.service.account.rpc,com.myz.npp.service.test.rpc
  protocol:
    name: dubbo
    port: 20881
  application:
    name: ${spring.application.name}-dubbo-provider
  registry:
    address: zookeeper://127.0.0.1:2181 #N/A
    file: ${user.home}/dubbo-cache/${spring.application.name}/dubbo.cache
npp:
  service:
    version: 1.0.0

# 超时时间（服务方跟消费方）、重试、异常处理
