## 自定义starter组件配置
aspect:
  printer:
    param:
      enabled: true
    retVal:
      enabled: false
distribute:
  id:
    snowflake:
      data-center-id: 1
      worker-id: 1
  lock:
    redis:
      enabled: false