server:
  port: 8081
  servlet:
    contextPath: /
spring:
  application:
    name: npp-service
  datasource:
    username: zjx_rd
    password: zaijiaxue
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.144.200:3306/npp0?characterEncoding=UTF-8&useUnicode=true&useSSL=false
  mvc:
    servlet:
      loadOnStartup: 1
  profiles:
    active: local
logging:
  level:
    PARAM-RETVAL-PRINTER: debug
  #    com.homelearning.user.dao.mapper: debug