spring:
  datasource:
    username: zjx_rd
    password: zaijiaxue
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.99.144.200:3306/npp?characterEncoding=UTF-8&useUnicode=true&useSSL=false