spring:
  shardingsphere:
    datasource:
      names: defaultDs,ds0,ds1
      defaultDs:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/npp?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/npp0?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/npp1?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
    sharding:
      defaultDataSourceName: defaultDs
      tables:
        npp_user:
          actualDataNodes: ds$->{0..1}.npp_user$->{0..2}
          databaseStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: ds$->{user_id.hashCode() % 2}
          tableStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: npp_user$->{user_id.hashCode() %3}
    props:
      sql:
        show: true