spring:
  shardingsphere:
    datasource:
      names: default,accountbookds0,accountbookds1,accountbookds2
      default:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/npp?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
      accountbookds0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/user_db0?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
      accountbookds1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/user_db1?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
      accountbookds2:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/user_db2?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
    sharding:
      defaultDataSourceName: default
      tables:
        npp_user:
          actualDataNodes: accountbookds$->{0..2}.npp_user$->{0..2}
          databaseStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: accountbookds$->{java.lang.Long.parseLong(user_id)% 3}
          tableStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: npp_user$->{java.lang.Long.parseLong(user_id) %3} # 用hashCode 容易出现负值 需要绝对值一下，但有可能重复
    props:
      sql:
        show: true
        simple: false