spring:
  shardingsphere:
    datasource:
      names: accountbookds0
      accountbookds0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://47.99.144.200:3306/account_book_ds0?characterEncoding=UTF-8
        username: zjx_rd
        password: zaijiaxue
        driver-class-name: com.mysql.jdbc.Driver
    sharding:
      tables:
        account_book:
          actualDataNodes: accountbookds0.account_book_$->{0..8}
          databaseStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: accountbookds0
          tableStrategy:
            inline:
              shardingColumn: user_id
              algorithmExpression: account_book_$->{java.lang.Long.parseLong(user_id) %9} # 用hashCode 容易出现负值 需要绝对值一下，但有可能重复
    props:
      sql:
        show: true
        simple: false