server:
  port: 8082
  servlet:
    contextPath: /
spring:
  application:
    name: npp-user-service
  mvc:
    servlet:
      loadOnStartup: 1
  profiles:
    active: local
    include: dubbo,mystarter,shardingjdbc
logging:
  level:
#    PARAM-RETVAL-PRINTER: debug
    com.myz.npp.service.user.dao.mapper: info
management:
  endpoints:
    web:
      exposure:
        include: "*"

distribute:
  id:
    snowflake:
      data-center-id: 1
      worker-id: 1