server:
  port: 80 # 域名直接指向服务器的80 端口  没有经过slb
  servlet:
    contextPath: /
spring:
  application:
    name: npp-web
  cloud:
    nacos:
      discovery:
        namespace: npp-public
        clusterName: npp-cluster
        server-addr: 127.0.0.1:8848
  mvc:
    servlet:
      loadOnStartup: 1
  profiles:
    active: local
    include: tomcat,dubbo,mystarter
logging:
  level:
    PARAM-RETVAL-PRINTER: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
npp:
  domain: http://test1.zaijiaxue.tech/
---
spring:
  profiles: local
server:
  port: 8888